spring:
  application:
    name: m2
    cloud:
      config:
        enabled: true
        uri: http://localhost:8081
    datasource:
      url: jdbc:mysql://localhost:3306/tartifasbd
      username: root
      password: 1234
    jpa:
      hibernate:
        ddl-auto: update
    mail:
      host: smtp.gmail.com
      port: 587
      username: duvanvh12@gmail.com
      password: csybsewhwltytjlf
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
              connectiontimeout: 5000
              timeout: 5000
              writetimeout: 5000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs