server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: tariff-service
          uri: lb://m1
          predicates:
            - Path=/api/tariffs/**
          filters:
            - StripPrefix=2

        - id: discount-number-service
          uri: lb://m2
          predicates:
            - Path=/api/desctnumber/**
          filters:
            - StripPrefix=2

        - id: discount-frequent-service
          uri: lb://m3
          predicates:
            - Path=/api/desctfrecu/**
          filters:
            - StripPrefix=2

        - id: special-tariff-service
          uri: lb://m4
          predicates:
            - Path=/api/specialtariffs/**
          filters:
            - StripPrefix=2

        - id: reservation-service
          uri: lb://m5
          predicates:
            - Path=/api/reserves/**
          filters:
            - StripPrefix=2

        - id: vehicle-management-service
          uri: lb://m6
          predicates:
            - Path=/api/vehicles/**
          filters:
            - StripPrefix=2

        - id: client-management-service
          uri: lb://m7
          predicates:
            - Path=/api/clients/**
          filters:
            - StripPrefix=2